### ISSUE TITLE
[macOS] This app seemed pretty fun to have but it's not actually running

### ISSUE THREAD

**Issue by Waynekosimoto** [daniel-trinh/twitch_chat_filter#1]
I keep getting messages that things were missing. Recently I've gotten really interested in terminal apps such as mpd + ncmpcpp, htop, etc so I wanted to try this but it's not working :(

../main.go:4:2: cannot find package "github.com/fluffle/goirc/client" in any of:
	/usr/local/go/src/github.com/fluffle/goirc/client (from $GOROOT)
	/Users/name/go/src/github.com/fluffle/goirc/client (from $GOPATH)
../main.go:5:2: cannot find package "github.com/gizak/termui" in any of:
	/usr/local/go/src/github.com/gizak/termui (from $GOROOT)
	/Users/name/go/src/github.com/gizak/termui (from $GOPATH)
../main.go:10:2: cannot find package "github.com/karlseguin/ccache" in any of:
	/usr/local/go/src/github.com/karlseguin/ccache (from $GOROOT)
	/Users/name/go/src/github.com/karlseguin/ccache (from $GOPATH)
../cli.go:5:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
	/Users/name/go/src/github.com/spf13/cobra (from $GOPATH)

**Comment by daniel-trinh** [comment]
have you tried running `go get <package>` for each of the missing packages? at some point i might vendor these dependencies, but right now the packages need to be fetched to run this

**Comment by daniel-trinh** [comment]
dependencies have been vendored, doing a pull on master or recloning this should work now

**Comment by Waynekosimoto** [comment]
I'm trying to go get all of them rn

**Comment by Waynekosimoto** [comment]
Literally as you posted

**Comment by Waynekosimoto** [comment]
Everything works but the message rate. The graph doesn't really look like one.

**Comment by Waynekosimoto** [comment]
[http://imgur.com/a/6JWfW](url)

**Comment by daniel-trinh** [comment]
that's a bug that seems to only happen in iterm2, it might have something to do with the font, but I haven't figured out a proper solution to it yet
